name: "gatk4_liftovervcf"
description: |
  Convert the genomic coordinates from one assembly to another.
  Based on a liftover chain file and a target reference fasta file,
  the tool converts the genomic coordinates of a vcf file and outputs
  successfully converted and rejected coordinates in separate vcf files.
keywords:
  - vcf
  - liftover
  - convert
tools:
  - gatk4:
      description: |
        Developed in the Data Sciences Platform at the Broad Institute, the toolkit offers a wide variety of tools
        with a primary focus on variant discovery and genotyping. Its powerful processing engine
        and high-performance computing features make it capable of taking on projects of any size.
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
      doi: 10.1158/1538-7445.AM2017-3590
      licence: ["Apache-2.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF file
      pattern: "*.{vcf}"
  - chain:
      type: file
      description: Liftover file to convert genomic coordinates. Can be downloaded [here](https://hgdownload.soe.ucsc.edu/downloads.html).
      pattern: "*.{chain}"
  - fasta:
      type: file
      description: The target reference fasta file
      pattern: "*.{fa,fasta}"
  - fai:
      type: file
      description: Index of the reference fasta file (required)
      pattern: "*.{fai}"
  - dict:
      type: file
      description: GATK sequence dictionary (can be created with gatk createsequencedictionary)
      pattern: "*.{dict}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - vcf:
      type: file
      description: Compressed vcf file containing the converted coordinates.
      pattern: "*.vcf.gz"
  - rejected_vcf:
      type: file
      description: Compressed vcf file containing the VCF coordinates that could not be converted.
      pattern: "*.vcf.gz"

authors:
  - "@SusiJo"
